.libPaths(c("/Users/pancho/.claude/jobs/867af780/tmp/rlib", .libPaths())); library(emphasis)
set.seed(5); tr <- ape::drop.fossil(ape::rlineage(0.5, 0.2, Tmax = 8))
while (ape::Ntip(tr) < 15 || ape::Ntip(tr) > 40) tr <- ape::drop.fossil(ape::rlineage(0.5,0.2,Tmax=8))
brts <- sort(ape::branching.times(tr), decreasing = TRUE); cat("tips", ape::Ntip(tr), "\n")
model <- c(0L,1L,0L); ip <- emphasis:::.expand_pars(c(0.6, -0.05, 0.2, 0.0), model)
lb <- emphasis:::.expand_pars(c(0, -0.5, 0, -0.5), model); ub <- emphasis:::.expand_pars(c(2, 0.5, 1, 0.5), model)
a <- emphasis:::augment_trees(brts, ip, 60L, 3000L, 1e4, 1e6, 1L, model, 0L, 1.0)
lw <- a$logf - a$logg; w <- exp(lw - max(lw)); w <- w / mean(w)
es <- function(trees) list(trees = trees, weights = w, rejected = 0L, rejected_overruns = 0L, rejected_lambda = 0L, rejected_zero_weights = 0L, time = 0, fhat = 0)
treesX <- lapply(a$trees, function(d) { d$pd <- 5 * d$pd; d })   # M covariate scaled 5x
m1 <- emphasis:::m_cpp(es(a$trees), ip, "rpd1", lb, ub, 1e-8, 1L, model, 0L, 1.0, NULL)
mX <- emphasis:::m_cpp(es(treesX),  ip, "rpd1", lb, ub, 1e-8, 1L, model, 0L, 1.0, NULL)
cat(sprintf("m_cpp (true pd) : beta0 %.5f gamma0 %.5f | betaM %.4f gammaM %.4f\n", m1$estimates[1], m1$estimates[5], m1$estimates[3], m1$estimates[7]))
cat(sprintf("m_cpp (pd x5)   : beta0 %.5f gamma0 %.5f | betaM %.4f gammaM %.4f\n", mX$estimates[1], mX$estimates[5], mX$estimates[3], mX$estimates[7]))
obj <- function(p, trees) { p8 <- emphasis:::.expand_pars(p, model); v <- -sum(w * emphasis:::eval_logf(p8, trees, model = model, link = 0L, rho = 1.0)$logf); if (!is.finite(v)) 1e10 else v }
o1 <- optim(c(0.6,-0.05,0.2,0), obj, trees = a$trees, method = "L-BFGS-B", lower = c(0.01,-0.5,0.01,-0.5), upper = c(2,0.5,1,0.5))
oX <- optim(c(0.6,-0.05,0.2,0), obj, trees = treesX,  method = "L-BFGS-B", lower = c(0.01,-0.5,0.01,-0.5), upper = c(2,0.5,1,0.5))
cat(sprintf("R optim/eval_logf (true pd): beta0 %.5f betaM %.4f gamma0 %.5f gammaM %.4f  Q=%.3f\n", o1$par[1], o1$par[2], o1$par[3], o1$par[4], -o1$value))
cat(sprintf("R optim/eval_logf (pd x5)  : beta0 %.5f betaM %.4f gamma0 %.5f gammaM %.4f  Q=%.3f\n", oX$par[1], oX$par[2], oX$par[3], oX$par[4], -oX$value))
cat(sprintf("Q(m_cpp estimate, real pd) = %.3f  vs Q(R optimum) = %.3f\n", -obj(c(m1$estimates[1], m1$estimates[3], m1$estimates[5], m1$estimates[7]), a$trees), -o1$value))
