.libPaths(c("/Users/pancho/.claude/jobs/867af780/tmp/rlib", .libPaths())); library(emphasis)
for (l in list(3, -1, 7.9, "foo")) cat("resolve_link(", format(l), ") ->", tryCatch(format(emphasis:::.resolve_link(l)), error=function(e) paste("ERROR:", conditionMessage(e))), "\n")
set.seed(4)
s3 <- replicate(200, { r <- simulate_tree(pars = c(0.6,0.1), max_t=4, model="cr", link=3); if (is.null(r$tes)) NA else ape::Ntip(r$tes) })
s0 <- replicate(200, { r <- simulate_tree(pars = c(0.6,0.1), max_t=4, model="cr", link=0); if (is.null(r$tes)) NA else ape::Ntip(r$tes) })
cat(sprintf("forward link=3: mean tips %.1f (surv %.2f); link=0: mean tips %.1f (surv %.2f)\n", mean(s3,na.rm=TRUE), mean(!is.na(s3)), mean(s0,na.rm=TRUE), mean(!is.na(s0))))
sim <- NULL; while (is.null(sim$tes) || ape::Ntip(sim$tes) < 10 || ape::Ntip(sim$tes) > 40) sim <- simulate_tree(pars = c(0.6,0.1), max_t=5, model="cr")
brts <- emphasis:::.extract_brts(sim); p8 <- c(0.6,0,0,0,0.1,0,0,0)
aug <- emphasis:::augment_trees(brts, p8, 5L, 200L, 1e4, 500, 1L, c(0L,0L,0L), 0L, 1.0)
for (l in c(0L, 3L)) cat("eval_logf link=", l, ":", tryCatch(format(emphasis:::eval_logf(p8, aug$trees, c(0L,0L,0L), l, 1.0)$logf[1:3]), error=function(e) paste("ERROR:", conditionMessage(e))), "\n")
r <- tryCatch({f <- estimate_rates(sim, method="mcem", model="cr", link=3, control=list(lower_bound=c(0.05,0), upper_bound=c(2,1), max_iter=2L, num_trees=20L, max_time=60)); paste("NO ERROR; pars", paste(round(f$pars,3), collapse=","))}, error=function(e) paste("ERROR:", conditionMessage(e)))
cat("estimate_rates link=3 ->", r, "\n")
r <- tryCatch({f <- estimate_rates(sim, method="mcem", model="cr", link=3, control=list(lower_bound=c(0.05,0), upper_bound=c(2,1), max_iter=2L, num_trees=20L, max_time=60, sampling="dynamic_fresh")); paste("NO ERROR; pars", paste(round(f$pars,3), collapse=","))}, error=function(e) paste("ERROR:", conditionMessage(e)))
cat("estimate_rates link=3 thinning ->", r, "\n")
