.libPaths(c("/Users/pancho/.claude/jobs/867af780/tmp/rlib", .libPaths())); library(emphasis)
set.seed(6)
sim <- NULL; while (is.null(sim$tes) || ape::Ntip(sim$tes) < 10 || ape::Ntip(sim$tes) > 40) sim <- simulate_tree(pars = c(0.6,0.1), max_t=5, model="cr")
r <- simulate_tree(tree=sim, pars=c(0.6,0.1), model="cr", useDDD=FALSE)
cat("useDDD=FALSE n_trees=1: names =", paste(names(r), collapse=","), " tas class:", class(r$tas)[1], " log_q:", r$log_q, "\n")
r3 <- simulate_tree(tree=sim, pars=c(0.6,0.1), model="cr", useDDD=FALSE, n_trees=3L)
cat("useDDD=FALSE n_trees=3: names =", paste(names(r3), collapse=","), " trees:", paste(sapply(r3$trees, function(x) class(x)[1]), collapse=","), " log_q len:", length(r3$log_q), "\n")
r1 <- simulate_tree(tree=sim, pars=c(0.6,0.1), model="cr", useDDD=TRUE)
cat("useDDD=TRUE: tas class:", class(r1$tas)[1], " names:", paste(names(r1), collapse=","), "\n")
