.libPaths(c("/Users/pancho/.claude/jobs/867af780/tmp/rlib-wave1", .libPaths()))
Sys.setenv(NOT_CRAN = "true")
library(emphasis); library(testthat)
cat("build:", system.file(package="emphasis"), "\n")
env <- new.env(parent = asNamespace("emphasis"))
res <- testthat::test_file("/Users/pancho/Code/emphasis/tests/testthat/test-thinning-envelope.R", env = env, reporter = "summary")
print(as.data.frame(res)[, c("test","nb","failed","skipped","error","warning","real")])
