// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_div_tree_cpp
Rcpp::List simulate_div_tree_cpp(Rcpp::NumericVector pars, Rcpp::IntegerVector model, double max_t, int max_N, int max_tries);
RcppExport SEXP _emphasis_simulate_div_tree_cpp(SEXP parsSEXP, SEXP modelSEXP, SEXP max_tSEXP, SEXP max_NSEXP, SEXP max_triesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type model(modelSEXP);
    Rcpp::traits::input_parameter< double >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< int >::type max_N(max_NSEXP);
    Rcpp::traits::input_parameter< int >::type max_tries(max_triesSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_div_tree_cpp(pars, model, max_t, max_N, max_tries));
    return rcpp_result_gen;
END_RCPP
}
// generateNonHomogeneousExpCpp
NumericVector generateNonHomogeneousExpCpp(int num_variates, NumericMatrix covariates, NumericVector parameters, double start_time, double max_time);
RcppExport SEXP _emphasis_generateNonHomogeneousExpCpp(SEXP num_variatesSEXP, SEXP covariatesSEXP, SEXP parametersSEXP, SEXP start_timeSEXP, SEXP max_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_variates(num_variatesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< double >::type start_time(start_timeSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(generateNonHomogeneousExpCpp(num_variates, covariates, parameters, start_time, max_time));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood
Rcpp::List loglikelihood(const std::vector<double>& pars, const Rcpp::List& trees, const Rcpp::NumericVector& logg, const std::string& plugin, const int num_rejected);
RcppExport SEXP _emphasis_loglikelihood(SEXP parsSEXP, SEXP treesSEXP, SEXP loggSEXP, SEXP pluginSEXP, SEXP num_rejectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type trees(treesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type logg(loggSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type plugin(pluginSEXP);
    Rcpp::traits::input_parameter< const int >::type num_rejected(num_rejectedSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood(pars, trees, logg, plugin, num_rejected));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mce
List rcpp_mce(const std::vector<double>& brts, const std::vector<double>& pars, int sample_size, int maxN, int max_missing, double max_lambda, const std::vector<double>& lower_bound, const std::vector<double>& upper_bound, double xtol_rel, int num_threads);
RcppExport SEXP _emphasis_rcpp_mce(SEXP brtsSEXP, SEXP parsSEXP, SEXP sample_sizeSEXP, SEXP maxNSEXP, SEXP max_missingSEXP, SEXP max_lambdaSEXP, SEXP lower_boundSEXP, SEXP upper_boundSEXP, SEXP xtol_relSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type brts(brtsSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type maxN(maxNSEXP);
    Rcpp::traits::input_parameter< int >::type max_missing(max_missingSEXP);
    Rcpp::traits::input_parameter< double >::type max_lambda(max_lambdaSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type lower_bound(lower_boundSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type upper_bound(upper_boundSEXP);
    Rcpp::traits::input_parameter< double >::type xtol_rel(xtol_relSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mce(brts, pars, sample_size, maxN, max_missing, max_lambda, lower_bound, upper_bound, xtol_rel, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mcem
List rcpp_mcem(const std::vector<double>& brts, const std::vector<double>& init_pars, int sample_size, int maxN, int max_missing, double max_lambda, const std::vector<double>& lower_bound, const std::vector<double>& upper_bound, double xtol_rel, int num_threads, bool copy_trees, Nullable<Function> rconditional);
RcppExport SEXP _emphasis_rcpp_mcem(SEXP brtsSEXP, SEXP init_parsSEXP, SEXP sample_sizeSEXP, SEXP maxNSEXP, SEXP max_missingSEXP, SEXP max_lambdaSEXP, SEXP lower_boundSEXP, SEXP upper_boundSEXP, SEXP xtol_relSEXP, SEXP num_threadsSEXP, SEXP copy_treesSEXP, SEXP rconditionalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type brts(brtsSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type init_pars(init_parsSEXP);
    Rcpp::traits::input_parameter< int >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type maxN(maxNSEXP);
    Rcpp::traits::input_parameter< int >::type max_missing(max_missingSEXP);
    Rcpp::traits::input_parameter< double >::type max_lambda(max_lambdaSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type lower_bound(lower_boundSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type upper_bound(upper_boundSEXP);
    Rcpp::traits::input_parameter< double >::type xtol_rel(xtol_relSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type copy_trees(copy_treesSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type rconditional(rconditionalSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mcem(brts, init_pars, sample_size, maxN, max_missing, max_lambda, lower_bound, upper_bound, xtol_rel, num_threads, copy_trees, rconditional));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mcm
List rcpp_mcm(List e_step, const std::vector<double>& init_pars, const std::string& plugin, const std::vector<double>& lower_bound, const std::vector<double>& upper_bound, double xtol_rel, int num_threads, Nullable<Function> rconditional);
RcppExport SEXP _emphasis_rcpp_mcm(SEXP e_stepSEXP, SEXP init_parsSEXP, SEXP pluginSEXP, SEXP lower_boundSEXP, SEXP upper_boundSEXP, SEXP xtol_relSEXP, SEXP num_threadsSEXP, SEXP rconditionalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type e_step(e_stepSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type init_pars(init_parsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type plugin(pluginSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type lower_bound(lower_boundSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type upper_bound(upper_boundSEXP);
    Rcpp::traits::input_parameter< double >::type xtol_rel(xtol_relSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type rconditional(rconditionalSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mcm(e_step, init_pars, plugin, lower_bound, upper_bound, xtol_rel, num_threads, rconditional));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_emphasis_simulate_div_tree_cpp", (DL_FUNC) &_emphasis_simulate_div_tree_cpp, 5},
    {"_emphasis_generateNonHomogeneousExpCpp", (DL_FUNC) &_emphasis_generateNonHomogeneousExpCpp, 5},
    {"_emphasis_loglikelihood", (DL_FUNC) &_emphasis_loglikelihood, 5},
    {"_emphasis_rcpp_mce", (DL_FUNC) &_emphasis_rcpp_mce, 10},
    {"_emphasis_rcpp_mcem", (DL_FUNC) &_emphasis_rcpp_mcem, 12},
    {"_emphasis_rcpp_mcm", (DL_FUNC) &_emphasis_rcpp_mcm, 8},
    {NULL, NULL, 0}
};

void remphasis_init(DllInfo *dll);
RcppExport void R_init_emphasis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    remphasis_init(dll);
}
