# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to calculate log likelihood of pars for a tree set,
#' @export
loglikelihood <- function(pars_r, trees, plugin) {
    .Call('_emphasis_loglikelihood', PACKAGE = 'emphasis', pars_r, trees, plugin)
}

simulate_pd_trees_cpp <- function(pars, max_t, repl, max_N) {
    .Call('_emphasis_simulate_pd_trees_cpp', PACKAGE = 'emphasis', pars, max_t, repl, max_N)
}

explore_grid_cpp <- function(par1, par2, par3, par4, max_t, num_repl, max_N) {
    .Call('_emphasis_explore_grid_cpp', PACKAGE = 'emphasis', par1, par2, par3, par4, max_t, num_repl, max_N)
}

#' function to perform one step of the E-M algorithm
#' @export
e_cpp <- function(brts, init_pars, sample_size, maxN, plugin, soc, max_missing, max_lambda, lower_bound, upper_bound, xtol_rel, num_threads) {
    .Call('_emphasis_rcpp_mce', PACKAGE = 'emphasis', brts, init_pars, sample_size, maxN, plugin, soc, max_missing, max_lambda, lower_bound, upper_bound, xtol_rel, num_threads)
}

#' function to perform one step of the E-M algorithm
#' @export
em_cpp <- function(brts, init_pars, sample_size, maxN, plugin, soc, max_missing, max_lambda, lower_bound, upper_bound, xtol_rel, num_threads, copy_trees, rconditional = NULL) {
    .Call('_emphasis_rcpp_mcem', PACKAGE = 'emphasis', brts, init_pars, sample_size, maxN, plugin, soc, max_missing, max_lambda, lower_bound, upper_bound, xtol_rel, num_threads, copy_trees, rconditional)
}

#' function to perform one step of the E-M algorithm
#' @export
m_cpp <- function(e_step, init_pars, plugin, lower_bound, upper_bound, xtol_rel, num_threads, rconditional = NULL) {
    .Call('_emphasis_rcpp_mcm', PACKAGE = 'emphasis', e_step, init_pars, plugin, lower_bound, upper_bound, xtol_rel, num_threads, rconditional)
}

