# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to calculate log likelihood of pars for a tree set,
#' @param pars vector of parameter values
#' @param trees list of trees, e.g. a multiPhylo object
#' @param logg vector of logg values
#' @param plugin name of used plugin
#' @param num_rejected number of rejected trees
#' @return list with the following entries: 
#' \itemize{
#'  \item{logf}{logf values}
#'  \item{log_w}{log of weight}
#'  \item{fhat}{fhat values}
#'  \item{N}{number of trees}
#' }
#' @export
loglikelihood <- function(pars, trees, logg, plugin, num_rejected) {
    .Call('_emphasis_loglikelihood', PACKAGE = 'emphasis', pars, trees, logg, plugin, num_rejected)
}



explore_grid_cpp <- function(par1, par2, par3, par4, max_t, num_repl, max_N) {
    .Call('_emphasis_explore_grid_cpp', PACKAGE = 'emphasis', par1, par2, par3, par4, max_t, num_repl, max_N)
}



